---
- hosts: "ping_server"
  remote_user: "ec2-user"
  gather_facts: no
  vars:
      ping_server: 172.31.10.95
  tasks:
    - name: Test connection     
      action: ping
    - debug:
          msg: "Test connection successful!" 
...