---
- hosts: 172.31.10.95
  remote_user: "ec2-user"
  gather_facts: no
  tasks:
    - name: Test connection
      any_errors_fatal: true 
      action: ping
      register: output

    - debug:
          msg: "Test connection successful!" 
...