---
- hosts: "ping_server"
  remote_user: "ec2-user"
  gather_facts: no
  vars_files:
    - ./vars/common_vars.yml
  tasks:
    - name: Test connection     
      action: ping
    - debug:
          msg: "Test connection successful!" 
...